name: Test on PR

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEVELOP
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Create env file
        run: |
          touch .env
          echo APP_NAME=${{ secrets.APP_NAME }} >> .env
          echo APP_PORT=${{ secrets.APP_PORT }} >> .env
          echo DB_DRIVER=${{ secrets.DB_DRIVER }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_DATABASE=${{ secrets.DB_DATABASE }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build --if-present
